### ISSUE TITLE
update ili file

### ISSUE THREAD

**Issue by mejiafabiandj** [SwissTierrasColombia/umleditor#1]
reload an .ili file or update it when source changes. useful to keep modularity between models

**Comment by Alexlizzt** [comment]
Ready [Release 3.6.9](https://github.com/AgenciaImplementacion/umleditor/releases/tag/v3.6.3.9)
Just some issues to consider..
   - Can't update translated models
   - Can't modify role definitions
   - Random problems after apply two times upload
   - Some documentation of Inderlis2Def can't have access to upload
