### ISSUE TITLE
REPORTS: ISO 19110 template

### ISSUE THREAD

**Issue by jonnykewin** [SwissTierrasColombia/umleditor#10]
Hola.

Cuando se actualiza o modifica un atributo de alguna clase, al generar el catalogo de objetos (ISO 19110 template), no aparece el atributo actulizado ni el atributo anterior de la clase en que se modifico.

**Comment by Alexlizzt** [comment]
Antes de utilizar el generador de catálogos, ¿guarda el modelo?, umleditor exporta el modelo que reconoce en el momento, si los cambios (actualizaciones o modificaciones de elementos del modelo) no se guardan, mantiene la anterior instancia del ultimo guardado.

**Comment by jonnykewin** [comment]
![image](https://user-images.githubusercontent.com/37425928/44045038-06c5f6c6-9eed-11e8-93ac-928adc352f1e.png)

En la ultima versión del modelo se actualizaron ciertos atributos, en la imagen anterior se puede ver uno de ellos.  Ahora bien, cuando genero el catalogo para la ISO 19110 el atributo Destinación_Economica desaparece de la tabla de atributos de la clase, lo anterior sucede con cada uno de los atributos que fueron modificados.

**Comment by Alexlizzt** [comment]
Resuelto en: [Release 3.6.4.9](https://github.com/AgenciaImplementacion/umleditor/releases/tag/v.3.6.4.9)
