### ISSUE TITLE
ISO 19110 TEMPLATE

### ISSUE THREAD

**Issue by jonnykewin** [SwissTierrasColombia/umleditor#11]
Al generar el catalogo de objetos con esta herramienta no se actualiza la cardinalidad de los atributos:
![image](https://user-images.githubusercontent.com/37425928/44607816-426b9280-a7b7-11e8-9e62-11ed110879ef.png)

![image](https://user-images.githubusercontent.com/37425928/44607857-59aa8000-a7b7-11e8-93a8-bf829d2824b3.png)

Por ejemplo los atributos de la clase COL_Interesado

**Comment by jonnykewin** [comment]
Adicionalmente, las nuevas clases que se crean en el UMLeditor como por ejemplo Calificacion_No_Convencional no se crean en el ISO 19110 TEMPLATE

**Comment by MauricioAcosta** [comment]
Buen día, hemos revisado y si esta tomando los cambios, y la cardinalidad si se esta actualizando, recuerda aplicar cada cambio que realices, y guardarlo.
![screenshot from 2018-10-28 18-15-15](https://user-images.githubusercontent.com/21351419/47623334-59dc3a00-dade-11e8-8b8e-ba5cf6399ae6.png)
![screenshot from 2018-10-28 18-24-04](https://user-images.githubusercontent.com/21351419/47623367-b6d7f000-dade-11e8-9376-0e10b10018c6.png)
![screenshot from 2018-10-28 18-16-28](https://user-images.githubusercontent.com/21351419/47623338-62347500-dade-11e8-8e28-103718c78aeb.png)
![screenshot from 2018-10-28 18-18-47](https://user-images.githubusercontent.com/21351419/47623341-65c7fc00-dade-11e8-9828-6549ab03e14e.png)
![screenshot from 2018-10-28 18-20-21](https://user-images.githubusercontent.com/21351419/47623342-68c2ec80-dade-11e8-9785-d72f5ae76452.png)
![screenshot from 2018-10-28 18-21-22](https://user-images.githubusercontent.com/21351419/47623345-6b254680-dade-11e8-886b-e115eddf0d57.png)
Y como puedes ver, si se están generando las clases nuevas.
