### ISSUE TITLE
support !!@CRS metattribute to coord domain

### ISSUE THREAD

**Issue by mejiafabiandj** [SwissTierrasColombia/umleditor#2]
see [https://github.com/claeis/ili2db/issues/87](url)

sample ili: https://github.com/claeis/ili2db/blob/434307b3e8cb8fe13589d41a22eebdacc6a6e6d7/test/data/Crs/CrsCoord23.ili

**Comment by Alexlizzt** [comment]
⚡️ Ready! [umleditor 3.6.3.7](https://github.com/AgenciaImplementacion/umleditor/releases/tag/v3.6.3.7)
