### ISSUE TITLE
Sistema de busqueda

### ISSUE THREAD

**Issue by jonnykewin** [SwissTierrasColombia/umleditor#8]
Sería de gran ayuda crear un sistema de búsqueda que facilite encontrar objetos, atributos y los dominios de los atributos. 

Gracias. Un saludo.

**Comment by Alexlizzt** [comment]
En el menú **Edit** se encuentra una opción llamada **Find/Replace** allí puedes realizar la búsqueda de cualquier elemento del modelo.
